name: Run deck 
on: push

jobs:
  deck-sync:
    runs-on: ubuntu-latest
    env:
      URL: ${{ secrets.KONG_ADDR }}
      METHOD: GET  # the method used to make the request. It is GET by default
    steps:
      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: "1.8.0"
      - name: decK ping
        id: decK_ping
        uses: sisodiya2421/pinger@master
        with:
          command: "ping ${{ secrets.KONG_ADDR }}"
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Run deck sync
        run: deck sync --kong-addr ${{ secrets.KONG_ADDR }}


