name: Run deck 
on: push

jobs:
  deck-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: "1.8.0"
      - name: decK ping
        id: decK_ping
        uses: actions/checkout@v2
        with:
          command: "ping"
          options: "--kong-addr ${{ secrets.KONG_ADDR }}"
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Run deck sync
        run: deck sync --kong-addr ${{ secrets.KONG_ADDR }}


